const DEFAULT_WAIT_TIME_INTERVAL = 5000;
const LAUNCH_DEFAULT_URL = 'http://localhost:4200/dashboard';

exports.DEFAULT_WAIT_TIME_INTERVAL = DEFAULT_WAIT_TIME_INTERVAL;
exports.LAUNCH_DEFAULT_URL = LAUNCH_DEFAULT_URL;
